theme = "terminal"

[editor]
# Sync clipboard with system clipboard
default-yank-register = "+"

popup-border = "all"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"

[keys.select]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
